[kernel-image]
kernel-app-modules = ["kernel-stack-monitor", "rustlet-stack-monitor"]

[root.package]
name = "NullSecurityDomain"
aid = "A0:00:00:47:50:4F:53:01"

[root.instance]
aid = "A0:00:00:47:50:4F:53:01"
install_bytes = "FF:FF:FF"

[[root.packages]]
path = "./rustlets/tests/minimal_valid_test"

[[root.packages.instances]]
aid = "A0:00:00:47:50:4F:53:16"
install_bytes = ""
