[root.package]
name = "NullSecurityDomain"
aid = "A0:00:00:47:50:4F:53:01"

[root.instance]
aid = "A0:00:00:47:50:4F:53:01"
install_bytes = "FF:FF:FF"

[[root.packages]]
path = "./rustlets/tests/minimal_valid_test"

[[root.packages]]
path = "./rustlets/tests/apdus_test"

[[root.packages]]
path = "./rustlets/tests/crypto_test"

[[root.packages]]
path = "./rustlets/tests/ecdh_test"

[[root.packages]]
path = "./rustlets/tests/state_test"

[[root.packages]]
path = "./rustlets/tests/serialization_test"

[[root.packages]]
path = "./rustlets/tests/stack_overflow_test"

[[root.packages]]
path = "./rustlets/tests/alloc_free_test"

[[root.packages]]
path = "./rustlets/tests/heap_form_test"

[[root.packages]]
path = "./rustlets/tests/string_test"

[[root.packages]]
path = "./rustlets/tests/termination_test"
