register_embedded_rustlets! {
    {
        name: COMPLETE_SECURITY_DOMAIN,
        aid_const: COMPLETE_SECURITY_DOMAIN_AID,
        getter: complete_security_domain_fae,
        selected_cfg: oxide_se_embedded_only_complete_security_domain,
        crate_dir: "rustlets/complete_security_domain",
        bin_name: "complete_security_domain",
        env_var: "OXIDE_SE_COMPLETE_SECURITY_DOMAIN_FAE_PATH",
        minimal: false,
        aid: [0xA0, 0x00, 0x00, 0x47, 0x50, 0x4F, 0x53, 0x06],
    },
    {
        name: RUSTLET_APDUS_TEST,
        aid_const: RUSTLET_APDUS_TEST_AID,
        getter: rustlet_apdus_test_fae,
        selected_cfg: oxide_se_embedded_only_rustlet_apdus_test,
        crate_dir: "rustlets/tests/apdus_test",
        bin_name: "rustlet_apdus_test",
        env_var: "OXIDE_SE_RUSTLET_APDUS_TEST_FAE_PATH",
        minimal: false,
        aid: [0xA0, 0x00, 0x00, 0x47, 0x50, 0x4F, 0x53, 0x1B],
    },
    {
        name: RUSTLET_CRYPTO_TEST,
        aid_const: RUSTLET_CRYPTO_TEST_AID,
        getter: rustlet_crypto_test_fae,
        selected_cfg: oxide_se_embedded_only_rustlet_crypto_test,
        crate_dir: "rustlets/tests/crypto_test",
        bin_name: "rustlet_crypto_test",
        env_var: "OXIDE_SE_RUSTLET_CRYPTO_TEST_FAE_PATH",
        minimal: false,
        aid: [0xA0, 0x00, 0x00, 0x47, 0x50, 0x4F, 0x53, 0x1C],
    },
    {
        name: RUSTLET_ECDH_TEST,
        aid_const: RUSTLET_ECDH_TEST_AID,
        getter: rustlet_ecdh_test_fae,
        selected_cfg: oxide_se_embedded_only_rustlet_ecdh_test,
        crate_dir: "rustlets/tests/ecdh_test",
        bin_name: "rustlet_ecdh_test",
        env_var: "OXIDE_SE_RUSTLET_ECDH_TEST_FAE_PATH",
        minimal: false,
        aid: [0xA0, 0x00, 0x00, 0x47, 0x50, 0x4F, 0x53, 0x1E],
    },
    {
        name: RUSTLET_STATE_TEST,
        aid_const: RUSTLET_STATE_TEST_AID,
        getter: rustlet_state_test_fae,
        selected_cfg: oxide_se_embedded_only_rustlet_state_test,
        crate_dir: "rustlets/tests/state_test",
        bin_name: "rustlet_state_test",
        env_var: "OXIDE_SE_RUSTLET_STATE_TEST_FAE_PATH",
        minimal: false,
        aid: [0xA0, 0x00, 0x00, 0x47, 0x50, 0x4F, 0x53, 0x10],
    },
    {
        name: RUSTLET_ALLOC_FREE_TEST,
        aid_const: RUSTLET_ALLOC_FREE_TEST_AID,
        getter: rustlet_alloc_free_test_fae,
        selected_cfg: oxide_se_embedded_only_rustlet_alloc_free_test,
        crate_dir: "rustlets/tests/alloc_free_test",
        bin_name: "rustlet_alloc_free_test",
        env_var: "OXIDE_SE_RUSTLET_ALLOC_FREE_TEST_FAE_PATH",
        minimal: false,
        aid: [0xA0, 0x00, 0x00, 0x47, 0x50, 0x4F, 0x53, 0x13],
    },
    {
        name: RUSTLET_SERIALIZATION_TEST,
        aid_const: RUSTLET_SERIALIZATION_TEST_AID,
        getter: rustlet_serialization_test_fae,
        selected_cfg: oxide_se_embedded_only_rustlet_serialization_test,
        crate_dir: "rustlets/tests/serialization_test",
        bin_name: "rustlet_serialization_test",
        env_var: "OXIDE_SE_RUSTLET_SERIALIZATION_TEST_FAE_PATH",
        minimal: false,
        aid: [0xA0, 0x00, 0x00, 0x47, 0x50, 0x4F, 0x53, 0x19],
    },
    {
        name: RUSTLET_STACK_OVERFLOW_TEST,
        aid_const: RUSTLET_STACK_OVERFLOW_TEST_AID,
        getter: rustlet_stack_overflow_test_fae,
        selected_cfg: oxide_se_embedded_only_rustlet_stack_overflow_test,
        crate_dir: "rustlets/tests/stack_overflow_test",
        bin_name: "rustlet_stack_overflow_test",
        env_var: "OXIDE_SE_RUSTLET_STACK_OVERFLOW_TEST_FAE_PATH",
        minimal: false,
        aid: [0xA0, 0x00, 0x00, 0x47, 0x50, 0x4F, 0x53, 0x1D],
    },
    {
        name: RUSTLET_HEAP_FORM_TEST,
        aid_const: RUSTLET_HEAP_FORM_TEST_AID,
        getter: rustlet_heap_form_test_fae,
        selected_cfg: oxide_se_embedded_only_rustlet_heap_form_test,
        crate_dir: "rustlets/tests/heap_form_test",
        bin_name: "rustlet_heap_form_test",
        env_var: "OXIDE_SE_RUSTLET_HEAP_FORM_TEST_FAE_PATH",
        minimal: false,
        aid: [0xA0, 0x00, 0x00, 0x47, 0x50, 0x4F, 0x53, 0x12],
    },
    {
        name: RUSTLET_ISOLATION_FAULT_TEST,
        aid_const: RUSTLET_ISOLATION_FAULT_TEST_AID,
        getter: rustlet_isolation_fault_test_fae,
        selected_cfg: oxide_se_embedded_only_rustlet_isolation_fault_test,
        crate_dir: "rustlets/tests/isolation_fault_test",
        bin_name: "rustlet_isolation_fault_test",
        env_var: "OXIDE_SE_RUSTLET_ISOLATION_FAULT_TEST_FAE_PATH",
        minimal: false,
        aid: [0xA0, 0x00, 0x00, 0x47, 0x50, 0x4F, 0x53, 0x17],
    },
    {
        name: RUSTLET_MINIMAL_VALID_TEST,
        aid_const: RUSTLET_MINIMAL_VALID_TEST_AID,
        getter: rustlet_minimal_valid_test_fae,
        selected_cfg: oxide_se_embedded_only_rustlet_minimal_valid_test,
        crate_dir: "rustlets/tests/minimal_valid_test",
        bin_name: "rustlet_minimal_valid_test",
        env_var: "OXIDE_SE_RUSTLET_MINIMAL_VALID_TEST_FAE_PATH",
        minimal: true,
        aid: [0xA0, 0x00, 0x00, 0x47, 0x50, 0x4F, 0x53, 0x16],
    },
    {
        name: RUSTLET_GETTING_STARTED_TEST,
        aid_const: RUSTLET_GETTING_STARTED_TEST_AID,
        getter: rustlet_getting_started_test_fae,
        selected_cfg: oxide_se_embedded_only_rustlet_getting_started_test,
        crate_dir: "rustlets/tests/getting_started_test",
        bin_name: "rustlet_getting_started_test",
        env_var: "OXIDE_SE_RUSTLET_GETTING_STARTED_TEST_FAE_PATH",
        minimal: true,
        aid: [0xA0, 0x00, 0x00, 0x47, 0x50, 0x4F, 0x53, 0x20],
    },
    {
        name: RUSTLET_STRING_TEST,
        aid_const: RUSTLET_STRING_TEST_AID,
        getter: rustlet_string_test_fae,
        selected_cfg: oxide_se_embedded_only_rustlet_string_test,
        crate_dir: "rustlets/tests/string_test",
        bin_name: "rustlet_string_test",
        env_var: "OXIDE_SE_RUSTLET_STRING_TEST_FAE_PATH",
        minimal: false,
        aid: [0xA0, 0x00, 0x00, 0x47, 0x50, 0x4F, 0x53, 0x14],
    },
    {
        name: RUSTLET_TRAMPOLINE_RETURN_TEST,
        aid_const: RUSTLET_TRAMPOLINE_RETURN_TEST_AID,
        getter: rustlet_trampoline_return_test_fae,
        selected_cfg: oxide_se_embedded_only_rustlet_trampoline_return_test,
        crate_dir: "rustlets/tests/trampoline_return_test",
        bin_name: "rustlet_trampoline_return_test",
        env_var: "OXIDE_SE_RUSTLET_TRAMPOLINE_RETURN_TEST_FAE_PATH",
        minimal: false,
        aid: [0xA0, 0x00, 0x00, 0x47, 0x50, 0x4F, 0x53, 0x15],
    },
    {
        name: RUSTLET_TERMINATION_TEST,
        aid_const: RUSTLET_TERMINATION_TEST_AID,
        getter: rustlet_termination_test_fae,
        selected_cfg: oxide_se_embedded_only_rustlet_termination_test,
        crate_dir: "rustlets/tests/termination_test",
        bin_name: "rustlet_termination_test",
        env_var: "OXIDE_SE_RUSTLET_TERMINATION_TEST_FAE_PATH",
        minimal: false,
        aid: [0xA0, 0x00, 0x00, 0x47, 0x50, 0x4F, 0x53, 0x11],
    },
}
